;; -*- mode: emacs-lisp; coding: emacs-mule; -*-
;; --------------------------------------------------------------------------
;; Desktop File for Emacs
;; --------------------------------------------------------------------------
;; Created Tue Sep 29 13:28:02 2015
;; Desktop file format version 206
;; Emacs version 24.4.51.2
(setq revive:frame-configuration-to-restore
  '(progn ))

;; Global section:
(setq desktop-saved-frameset [frameset 1 (22026 33746 840146 0) (desktop . "206") "tiagoinacio@iopo0263.local" nil nil ((((font-backend mac-ct ns) (fontsize . 0) (font . "-*-Menlo-normal-normal-normal-*-12-*-*-*-m-0-iso10646-1") (border-width . 0) (internal-border-width . 0) (vertical-scroll-bars) (foreground-color . "black") (background-color . "white") (line-spacing) (left-fringe . 3) (right-fringe . 11) (menu-bar-lines . 1) (tool-bar-lines . 1) (title) (icon-type) (auto-raise) (auto-lower) (cursor-type . box) (scroll-bar-width . 0) (alpha) (fullscreen) (background-mode . light) (fringe) (display-type . color) (cursor-color . "HotPink") (border-color . "Blue") (mouse-color . "sienna3") (visibility) (frameset--id . "1F62-B5CE-0F44-A09F") (frameset--mini t . t) (height . 35) (width . 80) (modeline . t) (minibuffer . t) (unsplittable) (left . 100) (top . 100) (right-divider-width . 0) (bottom-divider-width . 0) (icon-name) (display . "iopo0263.local") (explicit-name . t) (tool-bar-position . top)) ((min-height . 4) (min-width . 10) (min-height-ignore . 2) (min-width-ignore . 4) (min-height-safe . 1) (min-width-safe . 2) (min-pixel-height . 56) (min-pixel-width . 70) (min-pixel-height-ignore . 28) (min-pixel-width-ignore . 28) (min-pixel-height-safe . 14) (min-pixel-width-safe . 14)) leaf (pixel-width . 574) (pixel-height . 475) (total-width . 82) (total-height . 33) (normal-height . 1.0) (normal-width . 1.0) (buffer " *empty*" (selected . t) (hscroll . 0) (fringes 3 11 nil) (margins nil) (scroll-bars 0 0 t nil) (vscroll . 0) (dedicated) (point . 1) (start . 1))))])
(setq desktop-missing-file-warning nil)
(setq tags-file-name nil)
(setq tags-table-list nil)
(setq search-ring nil)
(setq regexp-search-ring nil)
(setq register-alist nil)
(setq file-name-history '("~/Library/Preferences/Aquamacs Emacs/Packages/elpa/w3-4.0.49/w3-autoloads.el" "~/Library/Preferences/Aquamacs Emacs/Packages/elpa/tern-auto-complete-20150611.639/tern-auto-complete-autoloads.el" "~/Library/Preferences/Aquamacs Emacs/Packages/elpa/tern-20150830.1256/tern-autoloads.el" "~/Library/Preferences/Aquamacs Emacs/Packages/elpa/sublime-themes-20150915.3/sublime-themes-autoloads.el" "~/Library/Preferences/Aquamacs Emacs/Packages/elpa/rainbow-delimiters-20150320.17/rainbow-delimiters-autoloads.el" "~/Library/Preferences/Aquamacs Emacs/Packages/elpa/powerline-evil-20140517.1/powerline-evil-autoloads.el" "~/Library/Preferences/Aquamacs Emacs/Packages/elpa/powerline-20150922.1143/powerline-autoloads.el" "~/Library/Preferences/Aquamacs Emacs/Packages/elpa/ov-20150311.2228/ov-autoloads.el" "~/Library/Preferences/Aquamacs Emacs/Packages/elpa/neotree-20150911.2204/neotree-autoloads.el" "~/Library/Preferences/Aquamacs Emacs/Packages/elpa/magit-20150928.1706/magit-autoloads.el" "~/Library/Preferences/Aquamacs Emacs/Packages/elpa/git-commit-20150903.1204/git-commit-autoloads.el" "~/Library/Preferences/Aquamacs Emacs/Packages/elpa/with-editor-20150921.1018/with-editor-autoloads.el" "~/Library/Preferences/Aquamacs Emacs/Packages/elpa/magit-popup-20150920.646/magit-popup-autoloads.el" "~/Library/Preferences/Aquamacs Emacs/Packages/elpa/linum-relative-20150927.24/linum-relative-autoloads.el" "~/Library/Preferences/Aquamacs Emacs/Packages/elpa/js2-refactor-20150913.2126/js2-refactor-autoloads.el" "~/Library/Preferences/Aquamacs Emacs/Packages/elpa/multiple-cursors-20150710.456/multiple-cursors-autoloads.el" "~/Library/Preferences/Aquamacs Emacs/Packages/elpa/s-20150924.406/s-autoloads.el" "~/Library/Preferences/Aquamacs Emacs/Packages/elpa/yasnippet-20150927.1716/yasnippet-autoloads.el" "~/Library/Preferences/Aquamacs Emacs/Packages/elpa/helm-projectile-20150917.551/helm-projectile-autoloads.el" "~/Library/Preferences/Aquamacs Emacs/Packages/elpa/projectile-20150911.844/projectile-autoloads.el"))

;; Buffer section -- buffers listed in same order as in buffer list:
